# Generated by Django 3.0.5 on 2020-04-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
