# Generated by Django 3.0.5 on 2020-05-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_test_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
            ],
        ),
    ]
