# Generated by Django 3.0.5 on 2020-05-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=20)),
                ('visit_times_today', models.IntegerField(default=0)),
                ('visit_times_all', models.IntegerField(default=0)),
            ],
        ),
    ]
