# Generated by Django 3.0.5 on 2020-05-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0004_visitinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitinformation',
            old_name='data',
            new_name='date',
        ),
    ]
