# Generated by Django 3.0.5 on 2020-07-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0006_leave_messag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leave_Messag',
            new_name='Leave_Message',
        ),
    ]
