# Generated by Django 3.0.5 on 2020-07-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0007_auto_20200718_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leave_Message',
            new_name='LeaveMessage',
        ),
    ]
