# Generated by Django 3.0.5 on 2020-07-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0008_auto_20200718_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemessage',
            name='leave_message_time',
            field=models.DateTimeField(),
        ),
    ]
