# Generated by Django 3.0.5 on 2020-07-22 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0009_auto_20200722_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemessage',
            name='leave_message_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
