# Generated by Django 3.0.5 on 2020-07-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0011_auto_20200722_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemessage',
            name='leave_message_time',
            field=models.CharField(max_length=20),
        ),
    ]
