# Generated by Django 2.2.14 on 2020-08-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0012_auto_20200722_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_user', models.CharField(max_length=20)),
                ('is_sign_today', models.BooleanField(default=0)),
                ('sign_total', models.IntegerField(default=0)),
                ('sign_continuous', models.IntegerField(default=0)),
                ('sign_last_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SignRefresh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_refresh_time', models.CharField(max_length=20)),
            ],
        ),
    ]
