# Generated by Django 2.2.14 on 2020-09-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0013_sign_signrefresh'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_user', models.CharField(max_length=20)),
                ('register_pwd', models.CharField(max_length=20)),
            ],
        ),
    ]
